# Generated by Django 5.2.3 on 2025-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_feria', models.CharField(max_length=50, unique=True, verbose_name='ID de la Feria')),
                ('nombre_feria', models.CharField(max_length=200, verbose_name='Nombre de la Feria')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('horario', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('completo', 'Completo')], max_length=20, verbose_name='Horario')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación / Zona')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('tipo_feria', models.CharField(choices=[('artesanias', 'Artesanías'), ('alimentos', 'Alimentos'), ('ropa', 'Ropa'), ('mixto', 'Mixto'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo de Feria')),
                ('costo_participacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Participación (USD)')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Estado')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite Inscripción')),
                ('forma_inscripcion', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('online', 'Online'), ('ambos', 'Ambos')], max_length=20, null=True, verbose_name='Forma de Inscripción')),
                ('num_permisos', models.IntegerField(blank=True, null=True, verbose_name='# Permisos Emitidos')),
                ('servicios', models.CharField(blank=True, max_length=200, verbose_name='Servicios Disponibles')),
                ('normas', models.TextField(blank=True, verbose_name='Requisitos / Normas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feria',
                'verbose_name_plural': 'Ferias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
